#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 13) buffer co {
    coherent restrict int count[];
};

uniform uint stride;
uniform uint countInt;

void main() {
    uint index = gl_GlobalInvocationID.x * (stride * 2) + (stride * 2) - 1;

    if (index >= countInt) return;

    count[index] = count[index - stride] + count[index];

    /*
    essentially:

    int upper = count[index];
    int lower = count[index - stride];

    count[index] = upper + lower;

    we set the upper value to the upper and lower values added together (upsweep!)
    */
}
