#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 13) buffer co {
    coherent restrict int count[];
};

uniform uint stride;
uniform uint countInt;

void main() {
    uint index = gl_GlobalInvocationID.x * (stride * 2) + (stride * 2) - 1;

    if (index >= countInt) return;

    int upper = count[index]; // only global read once
    int lower = count[index - stride]; // hold the value of the lower value
    count[index - stride] = upper; // move the upper value down
    count[index] = upper + lower; // add the upper and lower values together and place it in the upper value
}
