#version 430 core

layout(local_size_x = 32, local_size_y = 4, local_size_z = 4) in;

layout(std430, binding = 3) buffer w {
    restrict int W[];
};

layout(std430, binding = 10) buffer ww {
    restrict readonly int WW[];
};

uniform int maxWidth;
uniform int maxHeight;
uniform int wxh; // maxWidth * maxHeight

const float exponent = 1000000.0;
const int zero = 0;

void main() {
    int y = int(gl_GlobalInvocationID.y);
    int z = int(gl_GlobalInvocationID.z);
    int x = int(gl_GlobalInvocationID.x);

    if (x >= maxWidth || y >= maxHeight || z >= maxWidth + 1) return;

    int yxw = y * maxWidth;
    int zxwxh = z * wxh;
    int current = x + yxw + zxwxh;

    int weight = WW[current];

    if (!(weight > zero)) return;

    W[current] = int(float(W[current]) / float(weight) * exponent);
}
