#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

struct Particle {
    float x;
    float y;
    float z;

    float u;
    float v;
    float w;
};

layout(std430, binding = 6) buffer p {
    coherent restrict readonly Particle P[];
};

layout(std430, binding = 7) buffer n {
    int index;
};

layout(std430, binding = 13) buffer co {
    coherent restrict int count[];
};

layout(std430, binding = 14) buffer ps {
    coherent restrict writeonly Particle PS[];
};

uniform uint width;
uniform uint height;

uniform int maxWidth;
uniform int maxHeight;

void main() {
    // width and height are given through uniforms for optimsation's sake
    uvec3 id = gl_GlobalInvocationID;

    int current = int(id.x + (id.y * width) + (id.z * width * height));

    if (current < index) {
        Particle particle = P[current];

        int cellIndex = int(particle.x) + (int(particle.y) * maxWidth) + (int(particle.z) * maxWidth * maxHeight);

        // The Part Where She Count Sorts You.

        int particleIndex = (atomicAdd(count[cellIndex + 1], -1) - 1);

        PS[particleIndex] = particle; // This is The Part Where She Count Sorts Us.
    }
}
