#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

struct Particle {
    float x;
    float y;
    float z;

    float u;
    float v;
    float w;
};

layout(std430, binding = 6) buffer p {
    coherent restrict writeonly Particle P[];
};

layout(std430, binding = 7) buffer n {
    int index;
};

layout(std430, binding = 12) buffer de {
    coherent writeonly int dedata[];
};

layout(std430, binding = 13) buffer co {
    coherent restrict int count[];
};

layout(std430, binding = 14) buffer ps {
    coherent restrict readonly Particle PS[];
};

uniform uint width;
uniform uint height;

uniform int maxWidth;
uniform int maxHeight;
uniform int wxh;
uniform int maxInt;

const float radius = 0.2;

void separateParticle(in int pIndex, inout vec3 position) {
    Particle particle = PS[pIndex];

    vec3 colliderPosition = vec3(particle.x, particle.y, particle.z);

    float dist = distance(position, colliderPosition);

    // theoretically this branch could be removed with some odd looking max() statements i think, probably not worth it
    if (dist > radius || dist == 0) return;

    dedata[0] = 10;

    float overlap = radius - dist;

    // we do half the collision now and then the other half is done when the particle its colliding with also does its collision calculation (enforces jacobi)
    position += normalize(position - colliderPosition) * (overlap * 0.5);
}


void main() {
    // width and height are given through uniforms for optimsation's sake
    uvec3 id = gl_GlobalInvocationID;

    int current = int(id.x + (id.y * width) + (id.z * width * height));

    if (current < index) {
        Particle particle = PS[current];

        int cellIndex = int(particle.x) + (int(particle.y) * maxWidth) + (int(particle.z) * maxWidth * maxHeight);

        int dXpos = min(cellIndex + 1, maxInt);
        int dYpos = min(cellIndex + maxWidth, maxInt);
        int dZpos = min(cellIndex + wxh, maxInt);

        int dXneg = max(cellIndex - 1, 0);
        int dYneg = max(cellIndex - maxWidth, 0);
        int dZneg = max(cellIndex - wxh, 0);

        // we get the count value at that position and the one in front to know the start and end indices of where the particles are
        // count[] has 1 extra value at the end to make this safe

        // we start with the x axis for better memory coalescing
        int westStart = count[dXneg];
        int westEnd = count[dXneg + 1]; // not the area of london
        int westCount = westEnd - westStart;

        int selfStart = count[cellIndex];
        int selfEnd = count[cellIndex + 1];
        int selfCount = selfEnd - selfStart;

        int eastStart = count[dXpos];
        int eastEnd = count[dXpos + 1]; //  not the other area of london
        int eastCount = eastEnd - eastStart;

        int downStart = count[dYneg];
        int downEnd = count[dYneg + 1];
        int downCount = downEnd - downStart;

        int upStart = count[dYpos];
        int upEnd = count[dYpos + 1];
        int upCount = upEnd - upStart;

        int southStart = count[dZneg];
        int southEnd = count[dZneg + 1]; // not the place in the uk
        int southCount = southEnd - southStart;

        int northStart = count[dZpos];
        int northEnd = count[dZpos + 1];
        int northCount = northEnd - northStart;

        vec3 posVec = vec3(particle.x, particle.y, particle.z);

        for (int i = 0; i < westCount; i++) {
            separateParticle(westStart + i, posVec);
        }

        for (int i = 0; i < selfCount; i++) {
            if (selfStart + i == current) continue;
            separateParticle(selfStart + i, posVec);
        }

        for (int i = 0; i < eastCount; i++) {
            separateParticle(eastStart + i, posVec);
        }

        for (int i = 0; i < downCount; i++) {
            separateParticle(downStart + i, posVec);
        }

        for (int i = 0; i < upCount; i++) {
            separateParticle(upStart + i, posVec);
        }

        for (int i = 0; i < southCount; i++) {
            separateParticle(southStart + i, posVec);
        }

        for (int i = 0; i < northCount; i++) {
            separateParticle(northStart + i, posVec);
        }

        particle.x = posVec.x;
        particle.y = posVec.y;
        particle.z = posVec.z;

        P[current] = particle;
    }
}
