#version 430 core

layout(local_size_x = 32, local_size_y = 4, local_size_z = 4) in;

layout(std430, binding = 1) buffer u {
    restrict int U[];
};

layout(std430, binding = 8) buffer uw {
    restrict readonly int UW[];
};

uniform int maxWidth;
uniform int maxHeight;
uniform int w1xh; // (maxWidth + 1) * maxHeight
uniform int maxWidthDPos; // maxWidth + 1

const float exponent = 1000000.0;
const int zero = 0;

void main() {
    int y = int(gl_GlobalInvocationID.y);
    int z = int(gl_GlobalInvocationID.z);
    int x = int(gl_GlobalInvocationID.x);

    if (x >= maxWidthDPos || y >= maxHeight || z >= maxWidth) return;

    int yxw = y * maxWidthDPos;
    int zxwxh = z * w1xh;
    int current = x + yxw + zxwxh;

    int weight = UW[current];

    if (!(weight > zero)) return;

    U[current] = int(float(U[current]) / float(weight) * exponent);
}
