#version 430 core

layout(local_size_x = 32, local_size_y = 2, local_size_z = 2) in;

layout(std430, binding = 4) buffer s {
    restrict readonly uint S[];
};

struct Cell {
    uint flags;

    float sTot;
};

layout(std430, binding = 5) buffer cell {
    restrict writeonly Cell cells[];
};

uniform int maxWidth;
uniform int maxHeight;
uniform int wxh;

const int one = 1;
const float onef = 1.0;
const uint two = 2u;
const Cell empty = Cell(0u, 0.0);

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID);

    int x = id.x;
    int y = id.y;
    int z = id.z;

    if (x <= 0 || y <= 0 || z <= 0 || x >= maxWidth - 1 || y >= maxHeight - 1 || z >= maxWidth - 1) return;

    int zxwxh = z * wxh;

    int index = x + (y * maxWidth) + zxwxh;

    uint thisS = S[index];

    if (thisS < two) {
        cells[index] = empty;
        return;
    }

    int dXpos = index + 1;
    int dYpos = index + maxWidth;
    int dZpos = index + wxh;

    int dXneg = index - 1;
    int dYneg = index - maxWidth;
    int dZneg = index - wxh;

    uint sXpos = uint(S[dXpos] > 0u);
    uint sXneg = uint(S[dXneg] > 0u);
    uint sYpos = uint(S[dYpos] > 0u);
    uint sYneg = uint(S[dYneg] > 0u);
    uint sZpos = uint(S[dZpos] > 0u);
    uint sZneg = uint(S[dZneg] > 0u);

    uint tot =
    sXpos +
    sXneg +
    sYpos +
    sYneg +
    sZpos +
    sZneg;

    if (tot == 0u) {
        cells[index] = empty;
        return;
    }

    uint flags =
    (sXpos << 0) |
    (sXneg << 1) |
    (sYpos << 2) |
    (sYneg << 3) |
    (sZpos << 4) |
    (sZneg << 5) |
    ((thisS >> 1) << 6);

    cells[index] = Cell(flags, onef / float(tot));
}
