#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

struct Particle {
    float x;
    float y;
    float z;

    float u;
    float v;
    float w;
};

layout(std430, binding = 6) buffer p {
    Particle P[];
};

layout(std430, binding = 7) buffer n {
    int index;
};

layout(std430, binding = 13) buffer co {
    int count[];
};

uniform uint width;
uniform uint height;

uniform int maxWidth;
uniform int maxHeight;

const float dT = 0.05; // standard minecraft tick delta time
const float gravity = -0.81;

const float dens = 1.22;
const float dragCoeff = 0.47;
const float crossSection = 0.1;
const float form = 0.5 * dens * crossSection * dragCoeff;

void main() {
    // width and height are given through uniforms for optimsation's sake
    uvec3 id = gl_GlobalInvocationID;

    int current = int(id.x + (id.y * width) + (id.z * width * height));

    if (current < index) {
        Particle particle = P[current];
        particle.u -= (abs(particle.u) * particle.u) * form * dT;
        particle.v -= (abs(particle.v) * particle.v) * form * dT;
        particle.w -= (abs(particle.w) * particle.w) * form * dT;
        //particle.v += gravity * dT;
        particle.x += particle.u * dT;
        particle.y += ((particle.v) * dT);
        particle.z += particle.w * dT;

        int cellIndex = int(particle.x) + (int(particle.y) * maxWidth) + (int(particle.z) * maxWidth * maxHeight);

        P[current] = particle;

        atomicAdd(count[cellIndex], 1);
    }
}
