#version 430 core

layout(local_size_x = 80, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 1) buffer u {
    coherent restrict int U[];
};

layout(std430, binding = 2) buffer v {
    coherent restrict int V[];
};

layout(std430, binding = 3) buffer w {
    coherent restrict int W[];
};

struct Cell {
    uint flags;

    float sTot;
};

layout(std430, binding = 5) buffer Scalar {
    coherent readonly restrict Cell cells[];
};

layout(std430, binding = 12) buffer de {
    coherent writeonly int dedata[];
};

uniform int maxWidth;
uniform int maxHeight;
uniform int wxh;
uniform int w1xh; // (maxWidth + 1) * maxHeight
uniform int wxh1; // maxWidth * (maxHeight + 1)
uniform int maxWidthDPos; // maxWidth + 1
uniform int maxHeightDPos; // maxHeight + 1

uniform int RB;

const float o = 1;
const int one = 1;
const uint uone = 1u;
const int two = 2;
const float exponent = 1000000.0; // overflows at >2147
const float invExponent = 1.0 / 1000000.0;
const float dThreshold = 0.001;

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID);

    int y = id.y;
    int z = id.z;

    int x = id.x * two + ((y + z + RB) & 1); // RB = 0 or 1, 0 = red, 1 = black


    int yxw = y * maxWidth;
    int zxwxh = z * wxh;
    int index = x + yxw + zxwxh;

    Cell cell = cells[index];

    float sTot = cell.sTot;

    if (sTot == 0.0) return; // sTot == 0 also if it itself is 0 as defined in scalar.comp, this closes out a secondary branch that could happen where s = 1 but stot = 0, now we only check scalar

    uint flags = cell.flags;

    uint sXpos = (flags >> 0) & uone;
    uint sXneg = (flags >> 1) & uone;
    uint sYpos = (flags >> 2) & uone;
    uint sYneg = (flags >> 3) & uone;
    uint sZpos = (flags >> 4) & uone;
    uint sZneg = (flags >> 5) & uone;

    int westIndex = x + (y * maxWidthDPos) + (z * w1xh);
    int eastIndex = (x + one) + (y * maxWidthDPos) + (z * w1xh);
    int bottomIndex = x + yxw + (z * wxh1);
    int topIndex = x + ((y + one) * maxWidth) + (z * wxh1);
    int southIndex = index;
    int northIndex = x + yxw + ((z + one) * wxh);

    float d = o *
    ((float(U[eastIndex]) * invExponent) -
    (float(U[westIndex]) * invExponent) +
    (float(V[topIndex]) * invExponent) -
    (float(V[bottomIndex]) * invExponent) +
    (float(W[northIndex]) * invExponent) -
    (float(W[southIndex]) * invExponent));

    if (abs(d) < dThreshold) return;

    // scalartot is the scalar for differentiating walls and other non-fluids
    // if scalartot is 6 then it scales the divergence normally because all 6 axis are fluids

    //atomicCompSwap(dedata[0], 0, W[southIndex]);

    sTot = d * sTot * exponent;

    U[westIndex] += int(sXneg * sTot); // west
    U[eastIndex] -= int(sXpos * sTot); // east
    V[bottomIndex] += int(sYneg * sTot); // bottom
    V[topIndex] -= int(sYpos * sTot); // top
    W[southIndex] += int(sZneg * sTot); // south
    W[northIndex] -= int(sZpos * sTot); // north
}
