#version 430 core

layout(local_size_x = 32, local_size_y = 4, local_size_z = 4) in;

layout(std430, binding = 1) buffer u {
    restrict int U[];
};

layout(std430, binding = 4) buffer s {
    restrict readonly uint S[];
};

uniform int maxWidth;
uniform int maxHeight;
uniform int wxh; // maxWidth * maxHeight
uniform int w1xh; // (maxWidth + 1) * maxHeight
uniform int maxWidthDPos; // maxWidth + 1

void main() {
    int y = int(gl_GlobalInvocationID.y);
    int z = int(gl_GlobalInvocationID.z);
    int x = int(gl_GlobalInvocationID.x);

    if (x >= maxWidthDPos || y >= maxHeight || z >= maxWidth) return;

    int yxw = y * maxWidthDPos;
    int zxwxh = z * w1xh;
    int current = x + yxw + zxwxh;

    int adjacentPos = min(x, maxWidth - 1) + (y * maxWidth) + (z * wxh);
    int adjacentNeg = max(adjacentPos - 1, 0);

    U[current] *= int((min(1u, S[adjacentPos]) * min(1u, S[adjacentNeg])));
}
