#version 430 core

layout(local_size_x = 32, local_size_y = 4, local_size_z = 4) in;

layout(std430, binding = 3) buffer w {
    restrict int W[];
};

layout(std430, binding = 4) buffer s {
    restrict readonly uint S[];
};

uniform int maxWidth;
uniform int maxHeight;
uniform int wxh; // maxWidth * maxHeight
uniform int maxWidthDPos; // maxWidth + 1

void main() {
    int y = int(gl_GlobalInvocationID.y);
    int z = int(gl_GlobalInvocationID.z);
    int x = int(gl_GlobalInvocationID.x);

    if (x >= maxWidth || y >= maxHeight || z >= maxWidthDPos) return;

    int yxw = y * maxWidth;
    int zxwxh = z * wxh;
    int current = x + yxw + zxwxh;

    int adjacentPos = x + (y * maxWidth) + (min(z, maxWidth - 1) * wxh);
    int adjacentNeg = max(adjacentPos - wxh, 0);

    W[current] *= int((min(1u, S[adjacentPos]) * min(1u, S[adjacentNeg])));
}
