preview.entrypoint=com.gtnewhorizons.galaxia.preview.GalaxiaPreviewCatalog
preview.sources=src/preview/java
production.project=../..
production.gradle.task=classes
screen.width=1920
screen.height=1080
gui.scale=2
screen.background=#101820
