package com.gtnewhorizons.galaxia.registry.celestial.asteroid;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.function.Predicate;
import java.util.stream.Stream;

import javax.annotation.Nonnull;

import com.gtnewhorizons.galaxia.registry.celestial.CelestialObjectId;
import com.gtnewhorizons.galaxia.registry.celestial.knowledge.CelestialDiscoveryWork;
import com.gtnewhorizons.galaxia.registry.celestial.knowledge.DiscoveryState;

/**
 * Mutable knowledge layer for one team's view of one resolved asteroid field.
 *
 * Resolved nodes are content; entries are player knowledge. Keeping those layers
 * separate lets modpack updates change asteroid definitions without deleting
 * saved discovery/prospecting progress.
 */
public final class MutableAsteroidFieldKnowledge implements AsteroidFieldKnowledge {

    private final List<AsteroidFieldNode> nodes;
    private final Map<MinorCelestialBodyId, Entry> entriesById;

    private MutableAsteroidFieldKnowledge(@Nonnull List<AsteroidFieldNode> nodes,
        @Nonnull Map<MinorCelestialBodyId, Entry> entriesById) {
        this.nodes = List.copyOf(nodes);
        this.entriesById = new LinkedHashMap<>(entriesById);
    }

    public static MutableAsteroidFieldKnowledge initialize(@Nonnull CelestialObjectId beltId,
        @Nonnull AsteroidFieldProfile profile) {
        List<AsteroidFieldNode> nodes = AsteroidFieldResolver.resolveAll(beltId, profile);
        Map<MinorCelestialBodyId, Entry> entries = new LinkedHashMap<>();
        for (AsteroidFieldNode node : nodes) {
            entries.put(
                node.id(),
                new Entry(
                    AsteroidFieldResolver.initialDetectionState(node),
                    AsteroidFieldResolver.initialOreKnowledge(node)));
        }
        return new MutableAsteroidFieldKnowledge(nodes, entries);
    }

    public static MutableAsteroidFieldKnowledge fromSnapshot(@Nonnull CelestialObjectId beltId,
        @Nonnull AsteroidFieldProfile profile, @Nonnull AsteroidFieldKnowledgeSnapshot snapshot) {
        if (snapshot.beltId() != beltId) {
            throw new IllegalStateException(
                "Asteroid snapshot belt does not match requested belt: " + snapshot.beltId());
        }

        List<AsteroidFieldNode> nodes = new ArrayList<>(AsteroidFieldResolver.resolveAll(beltId, profile));
        Map<Integer, AsteroidFieldNode> nodesByIndex = new LinkedHashMap<>();
        Map<MinorCelestialBodyId, Entry> entries = new LinkedHashMap<>();
        for (AsteroidFieldNode node : nodes) {
            nodesByIndex.put(node.index(), node);
            entries.put(
                node.id(),
                new Entry(
                    AsteroidFieldResolver.initialDetectionState(node),
                    AsteroidFieldResolver.initialOreKnowledge(node)));
        }

        Set<Integer> seen = new HashSet<>();
        for (AsteroidFieldKnowledgeSnapshot.Entry snapshotEntry : snapshot.entries()) {
            int index = snapshotEntry.index();
            AsteroidFieldNode node = nodesByIndex.get(index);
            if (node == null) {
                // The save may mention a node that is no longer generated by the
                // current profile. Keep it resolvable so existing player state
                // still has a body to point at.
                node = AsteroidFieldResolver.resolveSavedNode(beltId, profile, index);
                nodesByIndex.put(index, node);
                nodes.add(node);
            }
            if (!seen.add(index)) {
                throw new IllegalStateException(
                    "Asteroid snapshot contains duplicate index for " + beltId + ": " + index);
            }
            if (snapshotEntry.detectionState() == DiscoveryState.HIDDEN
                && snapshotEntry.oreKnowledgeState() != AsteroidOreKnowledgeState.UNKNOWN) {
                throw new IllegalStateException("Hidden asteroid snapshot entry cannot expose ore knowledge: " + index);
            }
            entries.put(node.id(), new Entry(snapshotEntry.detectionState(), snapshotEntry.oreKnowledgeState()));
        }
        nodes.sort(Comparator.comparingInt(AsteroidFieldNode::index));
        return new MutableAsteroidFieldKnowledge(nodes, entries);
    }

    @Override
    public List<AsteroidFieldNode> nodes() {
        return nodes;
    }

    @Override
    public Entry entryFor(@Nonnull MinorCelestialBodyId id) {
        Entry entry = entriesById.get(id);
        if (entry == null) {
            throw new IllegalArgumentException("Unknown asteroid node id: " + id);
        }
        return entry;
    }

    @Override
    public Optional<AsteroidFieldNode> nextDetectionCandidate() {
        return nextDetectionCandidate(node -> true);
    }

    @Override
    public Optional<AsteroidFieldNode> nextDetectionCandidate(@Nonnull Predicate<AsteroidFieldNode> scope) {
        return nextDetectionCandidate(scope, AsteroidFieldScanOrder.byIndex());
    }

    @Override
    public Optional<AsteroidFieldNode> nextDetectionCandidate(@Nonnull Predicate<AsteroidFieldNode> scope,
        @Nonnull Comparator<AsteroidFieldNode> order) {
        return scopedNodes(scope, order).filter(node -> entryFor(node.id()).detectionState() == DiscoveryState.HIDDEN)
            .findFirst();
    }

    @Override
    public boolean hasDetectionWork() {
        return hasDetectionWork(node -> true);
    }

    @Override
    public boolean hasDetectionWork(@Nonnull Predicate<AsteroidFieldNode> scope) {
        return nextDetectionCandidate(scope).isPresent();
    }

    @Override
    public boolean canProspect() {
        return canProspect(node -> true);
    }

    @Override
    public boolean canProspect(@Nonnull Predicate<AsteroidFieldNode> scope) {
        return !hasDetectionWork(scope);
    }

    @Override
    public Optional<AsteroidFieldNode> nextProspectingCandidate() {
        return nextProspectingCandidate(node -> true);
    }

    @Override
    public Optional<AsteroidFieldNode> nextProspectingCandidate(@Nonnull Predicate<AsteroidFieldNode> scope) {
        return nextProspectingCandidate(scope, AsteroidFieldScanOrder.byIndex());
    }

    @Override
    public Optional<AsteroidFieldNode> nextProspectingCandidate(@Nonnull Predicate<AsteroidFieldNode> scope,
        @Nonnull Comparator<AsteroidFieldNode> order) {
        if (!canProspect(scope)) return Optional.empty();
        // Prospecting advances one knowledge tier at a time. Signature comes
        // before profile so the UI can show partial ore knowledge first.
        Optional<AsteroidFieldNode> signatureCandidate = nextSignatureCandidate(scope, order);
        return signatureCandidate.isPresent() ? signatureCandidate : nextProfileCandidate(scope, order);
    }

    @Override
    public Optional<AsteroidFieldNode> nextSignatureCandidate(@Nonnull Predicate<AsteroidFieldNode> scope,
        @Nonnull Comparator<AsteroidFieldNode> order) {
        if (!canProspect(scope)) return Optional.empty();
        return scopedNodes(scope, order)
            .filter(node -> entryFor(node.id()).detectionState() == DiscoveryState.DISCOVERED)
            .filter(node -> entryFor(node.id()).oreKnowledgeState() == AsteroidOreKnowledgeState.UNKNOWN)
            .findFirst();
    }

    @Override
    public Optional<AsteroidFieldNode> nextProfileCandidate(@Nonnull Predicate<AsteroidFieldNode> scope,
        @Nonnull Comparator<AsteroidFieldNode> order) {
        if (!canProspect(scope) || nextSignatureCandidate(scope, order).isPresent()) return Optional.empty();
        return scopedNodes(scope, order)
            .filter(node -> entryFor(node.id()).detectionState() == DiscoveryState.DISCOVERED)
            .filter(node -> entryFor(node.id()).oreKnowledgeState() == AsteroidOreKnowledgeState.SIGNATURE)
            .findFirst();
    }

    @Override
    public Optional<CelestialDiscoveryWork> nextDiscoveryWork(@Nonnull Predicate<AsteroidFieldNode> scope,
        @Nonnull Comparator<AsteroidFieldNode> order) {
        Optional<AsteroidFieldNode> detection = nextDetectionCandidate(scope, order);
        if (detection.isPresent())
            return detection.map(node -> AsteroidFieldDiscoveryWork.from(AsteroidFieldScanPass.DETECTION, node));

        Optional<AsteroidFieldNode> signature = nextSignatureCandidate(scope, order);
        if (signature.isPresent())
            return signature.map(node -> AsteroidFieldDiscoveryWork.from(AsteroidFieldScanPass.SIGNATURE, node));

        return nextProfileCandidate(scope, order)
            .map(node -> AsteroidFieldDiscoveryWork.from(AsteroidFieldScanPass.PROFILE, node));
    }

    @Override
    public Entry detect(@Nonnull MinorCelestialBodyId id) {
        AsteroidFieldNode node = requireNode(id);
        Entry current = entryFor(id);
        if (current.detectionState() == DiscoveryState.DISCOVERED) return current;

        Entry updated = new Entry(DiscoveryState.DISCOVERED, AsteroidFieldResolver.oreKnowledgeAfterDetection(node));
        entriesById.put(id, updated);
        return updated;
    }

    @Override
    public Entry prospect(@Nonnull MinorCelestialBodyId id) {
        return prospect(id, node -> true);
    }

    @Override
    public Entry prospect(@Nonnull MinorCelestialBodyId id, @Nonnull Predicate<AsteroidFieldNode> scope) {
        AsteroidFieldNode node = requireNode(id);
        if (!scope.test(node)) {
            throw new IllegalArgumentException("Asteroid node is outside prospecting scope: " + id);
        }
        Entry current = entryFor(id);
        if (current.detectionState() == DiscoveryState.HIDDEN) {
            throw new IllegalStateException("Cannot prospect hidden asteroid node: " + id);
        }
        if (hasDetectionWork(scope)) {
            throw new IllegalStateException("Asteroid detection must finish before prospecting can start");
        }

        Entry updated = new Entry(DiscoveryState.DISCOVERED, nextOreKnowledgeState(current.oreKnowledgeState()));
        entriesById.put(id, updated);
        return updated;
    }

    @Override
    public Entry revealDiscovery(@Nonnull CelestialDiscoveryWork work, @Nonnull Predicate<AsteroidFieldNode> scope) {
        if (!(work instanceof AsteroidFieldDiscoveryWork asteroidWork)) {
            throw new IllegalArgumentException("Expected asteroid field discovery work");
        }
        if (asteroidWork.step() == AsteroidFieldScanPass.DETECTION) return detect(asteroidWork.asteroidId());
        return prospect(asteroidWork.asteroidId(), scope);
    }

    private static AsteroidOreKnowledgeState nextOreKnowledgeState(AsteroidOreKnowledgeState current) {
        return switch (current) {
            case UNKNOWN -> AsteroidOreKnowledgeState.SIGNATURE;
            case SIGNATURE, PROFILE -> AsteroidOreKnowledgeState.PROFILE;
        };
    }

    private Stream<AsteroidFieldNode> scopedNodes(@Nonnull Predicate<AsteroidFieldNode> scope,
        @Nonnull Comparator<AsteroidFieldNode> order) {
        return nodes.stream()
            .filter(scope)
            .sorted(order);
    }

    @Override
    public AsteroidFieldKnowledgeSnapshot snapshot(@Nonnull CelestialObjectId beltId) {
        return new AsteroidFieldKnowledgeSnapshot(
            beltId,
            nodes.stream()
                .filter(node -> entryFor(node.id()).detectionState() == DiscoveryState.DISCOVERED)
                .map(node -> {
                    Entry entry = entryFor(node.id());
                    return new AsteroidFieldKnowledgeSnapshot.Entry(
                        node.index(),
                        entry.detectionState(),
                        entry.oreKnowledgeState());
                })
                .toList());
    }

    private AsteroidFieldNode requireNode(@Nonnull MinorCelestialBodyId id) {
        return nodes.stream()
            .filter(
                node -> node.id()
                    .equals(id))
            .findFirst()
            .orElseThrow(() -> new IllegalArgumentException("Unknown asteroid node id: " + id));
    }
}
